export const Api_Urls = {
  login: 'http://localhost:3000/auth/login',
  register: 'http://localhost:3000/auth/register',
  getDoctors: 'http://localhost:3000/doctor',
  getPatientAppointments: 'http://localhost:3000/appointment/patient',
  getPatients: 'http://localhost:3000/patient',
  addAppointment: 'http://localhost:3000/appointment',
  getAvailableSessions: 'http://localhost:3000/appointment/availableSessions',
  getDoctorAppointmentsByName: 'http://localhost:3000/appointment/doctor',
  getPatientRequests: 'http://localhost:3000/appointment/patient/requests',
  getMedications: 'http://localhost:3000/medication',
  getPatientNextAppointment: 'http://localhost:3000/appointment/patient/next',
  getPatientNotPayed: 'http://localhost:3000/appointment/patient/notpayed',
  getPatientUpcoming: 'http://localhost:3000/appointment/patient/upcoming',
  getPatientUpcomingNumber: 'http://localhost:3000/appointment/patient/upcomingNumber',
  getPassedAppointment: 'http://localhost:3000/appointment/patient',
  getUpcomingAppointment: 'http://localhost:3000/appointment/patient/upcoming',
  getPatientByUsername: 'http://localhost:3000/patient',
  getDoctorByMatricule: 'http://localhost:3000/doctor',
};
