export const Api_Urls = {
  login: 'http://localhost:3000/auth/login',
  register: 'http://localhost:3000/auth/register',
  getDoctors: 'http://localhost:3000/doctor',
  getDoctorAppointmentsByName: 'http://localhost:3000/appointment/doctor',
  getPateintAppointments: 'http://localhost:3000/appointment/patient',
  getPateintRequests: 'http://localhost:3000/appointment/patient/requests',
  addAppointment: 'http://localhost:3000/appointment',
  getAvailableSessions: 'http://localhost:3000/appointment/availableSessions',
  getMedications: 'http://localhost:3000/medication',
  getPatientNextAppointment: 'http://localhost:3000/appointment/patient/next',
  getPatientNotPayed: 'http://localhost:3000/appointment/patient/notpayed',
  getPatientUpcoming: 'http://localhost:3000/appointment/patient/upcoming',
  getPatientUpcomingNumber: 'http://localhost:3000/appointment/patient/upcomingNumber',
  getPassedAppointement:'http://localhost:3000/appointment/patient',
  getUpcommingAppointment:'http://localhost:3000/appointment/patient/upcoming',
  getPatientByUsername:'http://localhost:3000/patient',
  getDoctorByMatricule:'http://localhost:3000/doctor',
  getUpcomingDoctorAppointments: 'http://localhost:3000/appointment/doctor/upcoming',
  deleteAppointmentByDoctor: 'http://localhost:3000/appointment/doctor'
};
